name: telemedicine_doctor
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <4.0.0"

dependencies:
  badges: ^3.1.2
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  emoji_picker_flutter: ^2.1.1
  encrypt: ^5.0.3
  equatable: ^2.0.5
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_svg: ^2.0.9
  hooks_riverpod: ^2.5.1
  image: ^4.2.0
  image_picker: ^1.0.8
  intl: ^0.19.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  photo_view: ^0.15.0
  shared_preferences: ^2.2.2
  svgaplayer_flutter: ^2.2.0
  transparent_image: ^2.0.1
  video_compress: ^3.1.2
  video_player: ^2.8.5
  zego_express_engine: ^3.12.5
  zego_zim: ^2.14.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/gift/
